use aaaa;

select * from xdywy


insert into xdywy values ('784','黄国军','','江西樟树','聂勇')
insert into xdywy values ('1367','张宝文','','江西樟树','聂勇')
insert into xdywy values ('1630','李艳锋','','江西樟树','聂勇')
insert into xdywy values ('3583','黄国红','','江西樟树','聂勇')
insert into xdywy values ('3882','邹建军','','江西樟树','聂勇')
insert into xdywy values ('4540','周强','','江西樟树','聂勇')
insert into xdywy values ('8021','杨艳平','','江西樟树','聂勇')
insert into xdywy values ('10776','廖水英','','江西樟树','聂勇')
insert into xdywy values ('11091','陈叶红','','江西樟树','聂勇')
insert into xdywy values ('11146','张艳英','','江西樟树','聂勇')
insert into xdywy values ('11227','傅影珍','','江西樟树','聂勇')
insert into xdywy values ('11527','何惠桃','','江西樟树','聂勇')
insert into xdywy values ('11899','熊芳','','江西樟树','聂勇')
insert into xdywy values ('11920','曾龙春','','江西樟树','聂勇')
insert into xdywy values ('12135','敖小燕','','江西樟树','聂勇')
insert into xdywy values ('12191','傅菊珍','','江西樟树','聂勇')
insert into xdywy values ('12303','段广多','','江西樟树','聂勇')
insert into xdywy values ('12308','黄新华','','江西樟树','聂勇')
insert into xdywy values ('21929','付樟飞','','江西樟树','聂勇')
insert into xdywy values ('22301','桂俊春','','江西樟树','聂勇')
insert into xdywy values ('37574','张志峰','','江西樟树','聂勇')
insert into xdywy values ('39443','付贵兰','','江西樟树','聂勇')
insert into xdywy values ('41204','周绍武','','江西樟树','聂勇')
insert into xdywy values ('44203','李平旦','','江西樟树','聂勇')
insert into xdywy values ('54727','刘香梅','','江西樟树','聂勇')
insert into xdywy values ('54959','张梦阳','','江西樟树','聂勇')
insert into xdywy values ('55009','朱辉','','江西樟树','聂勇')
insert into xdywy values ('57131','王娥','','江西樟树','聂勇')
insert into xdywy values ('12582','陈国平','','江西樟树','聂勇')
insert into xdywy values ('12583','卢海红','','江西樟树','聂勇')
insert into xdywy values ('12587','李贱如','','江西樟树','聂勇')
insert into xdywy values ('12672','肖少平','','江西樟树','聂勇')
insert into xdywy values ('12967','杨爱平','','江西樟树','聂勇')
insert into xdywy values ('14112','杨金梅','','江西樟树','聂勇')
insert into xdywy values ('14545','张妹琴','','江西樟树','聂勇')
insert into xdywy values ('15775','谢文娟','','江西樟树','聂勇')
insert into xdywy values ('18037','聂凤琴','','江西樟树','聂勇')
insert into xdywy values ('47336','黄玲','','江西樟树','聂勇')
insert into xdywy values ('47686','杨凯','','江西樟树','聂勇')
insert into xdywy values ('47895','邹力','','江西樟树','聂勇')
insert into xdywy values ('49285','胡珍桂','','江西樟树','聂勇')
insert into xdywy values ('50101','刘芳冰','','江西樟树','聂勇')
insert into xdywy values ('50763','雷芳','','江西樟树','聂勇')
insert into xdywy values ('51366','陈江波','','江西樟树','聂勇')
insert into xdywy values ('51643','桂文梁','','江西樟树','聂勇')
insert into xdywy values ('58217','郭新力','','江西樟树','聂勇')
